### ISSUE TITLE
support for parsing a string

### ISSUE THREAD

**Issue by benmonro** [hypermodules/changelog-parser#23]
currently it appears that changelog-parser only works w/ file paths.  however, i'd like to pass in a string (pulled from a github graphql query) rather than a file path.   is this possible?

for example:

```javascript
let md = "#some markdown in a changelog ... (versions, changes etc)";

let result = await parseChangelog(md);

console.log("the versions: ", result.versions) 
```

is this possible?  I'm not super familiar w/ line-reader but maybe something like this would help?  https://github.com/feross/string-to-stream

**Comment by ungoldman** [comment]
Hi @benmonro!

It looks line `line-reader` does have some support for streams -- see the streams section in their readme.

https://github.com/nickewing/line-reader#streams

I'm not sure if this is possible with `changelog-parser` right now, but it might be? If not I'm definitely open to a pull request to make your use case easier. It's been a few years since I wrote this, definitely starting to show its age :)

**Comment by benmonro** [comment]
Hey @ungoldman all good.  I like this tool a lot but I decided to  implement it with standard-version and Semver support using remark to process to ast.  Fun stuff.  🙂 https://github.com/benmonro/chast
